pull request for issue #14 - request to support channels,etc.
NLog/NLog.Etw pull request #15
Opened 2016-10-18 00:00 UTC by mfaulkinbury

Hello,
Please consider the issue that I just opened and the related pull request.  
I've added additional information to the readme.md file.
I'm looking forward to your feedback and an opportunity to contribute to this great repo.

Best,
Mike

2016-10-18 12:47 UTC, 304NotModified requested changes

2016-10-18 12:47 UTC, 304NotModified commented on NLog.Etw/NLogEtwExtendedTarget.cs
> -        [EventSource(Name = "LowLevelDesign-NLogEtwSource")]
why this change? It's a breaking change?

2016-10-18 12:47 UTC, 304NotModified commented on NLog.Etw/RegisterEvents/ReadMe.txt
> +﻿RegisteredEvents.EXE is a seld-extracting, self-installing package used to register the NLog ETW provider and channel-based log files.
do we need this files: readme.txt, RegisterEvents.EXE,  /RegisterEvents.SED, _EventRegisterUsersGuide.docx .bat files etc

2016-10-18 17:25 UTC, mfaulkinbury commented on NLog.Etw/NLogEtwExtendedTarget.cs
> -        [EventSource(Name = "LowLevelDesign-NLogEtwSource")]
From [this article](https://blogs.msdn.microsoft.com/vancem/2012/08/14/etw-in-c-controlling-which-events-get-logged-in-an-system-diagnostics-tracing-eventsource/):
"Finally, the EventSource above follows a ‘best practice’ of naming its ETW provider a good name FROM THE U SER’s POINT OF VIEW.   Names should at least start with your company name.  If you expect more than one EventSource for your company it is best to give them categories separated by ‘-‘.   This is the convention that Microsoft has been following for the last several years.  (e.g. Microsoft-Windows-DotNetRuntime). "

"LowLevelDesign-xxx" doesn't seem to be a "good name from the user's point of view" (it's not obvious what that refers to).  "NLog-xxx" seems more appropriate IMHO.

It's only a breaking change with respect to guidance.  We could add updated instructions to the readme file on how to dynamically consume the events using PerfView.

Thoughts?

2016-10-18 17:37 UTC, mfaulkinbury commented on NLog.Etw/RegisterEvents/ReadMe.txt
> +﻿RegisteredEvents.EXE is a seld-extracting, self-installing package used to register the NLog ETW provider and channel-based log files.
_EventRegisterUsersGuide.docx gets added with [Microsoft.Diagnostics.Tracing.EventRegister](https://www.nuget.org/packages/Microsoft.Diagnostics.Tracing.EventRegister/).  This package creates a new manifest by inspecting the event source during build.

The rest of the files are my attempt to make manifest registration easier.  I'm open to refactoring as needed or moving into a separate package if they seem to add too much friction.

2016-10-19 19:01 UTC, 304NotModified requested changes

2016-10-19 19:01 UTC, 304NotModified commented on NLog.Etw/packages.config
> +  <package id="Microsoft.Diagnostics.Tracing.EventSource.Redist" version="1.1.28" targetFramework="net45" />
The nuspec should be updated for this?

2016-10-19 19:01 UTC, 304NotModified commented on README.md
> +2. Run RegisterEvents.exe as Administrator.
This is old I guess?

2016-10-19 19:01 UTC, 304NotModified commented
Is this change backwards compatible?

2016-10-19 19:14 UTC, 304NotModified commented
Otherwise we could add a new target instead of changing the expended

2016-10-19 19:32 UTC, mfaulkinbury commented
This should be backward compatible (same NLog config leads to same output/ETW session).

2016-10-19 20:09 UTC, mfaulkinbury commented on NLog.Etw/packages.config
> +  <package id="Microsoft.Diagnostics.Tracing.EventSource.Redist" version="1.1.28" targetFramework="net45" />
NuGet pack was failing due to the content files reference. The package dependencies (NLog, Microsoft.Diagnostics.Tracing.EventSource.Redist) are added automagically.

2016-10-19 21:27 UTC, mfaulkinbury commented
I'd be fine with adding a new target as well. Your call.

Sent from my mobile phone

________________________________
From: Julian Verdurmen <notifications@github.com>
Sent: Wednesday, October 19, 2016 2:14:39 PM
To: NLog/NLog.Etw
Cc: Mike Faulkinbury; Author
Subject: Re: [NLog/NLog.Etw] pull request for issue #14 - request to support channels,etc. (#15)


Otherwise we could add a new target instead of changing the expended

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/NLog/NLog.Etw/pull/15#issuecomment-254912437>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AJdhizNzTD-o8WByiNS17_dKV0TRQ9Rrks5q1mwfgaJpZM4KZPLT>.

2016-10-19 21:43 UTC, 304NotModified commented
OK thx. No need for new target of backwards comp :)

2016-10-19 21:44 UTC, 304NotModified approved these changes

2016-10-19 21:45 UTC, merged

2016-10-19 21:47 UTC, 304NotModified commented
Releasing this one ASAP as NLog.ETW 4.1?

2016-10-25 18:51 UTC, mfaulkinbury commented
Were you going to push to NuGet?

From: Julian Verdurmen [mailto:notifications@github.com]
Sent: Wednesday, October 19, 2016 4:47 PM
To: NLog/NLog.Etw <NLog.Etw@noreply.github.com>
Cc: Mike Faulkinbury <mike@integrasource.com>; Author <author@noreply.github.com>
Subject: Re: [NLog/NLog.Etw] Support for channels (#15)


Releasing this one ASAP as NLog.ETW 4.1?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/NLog/NLog.Etw/pull/15#issuecomment-254950665>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AJdhi0qf5LqWWo3Hu6U3HGoiWAMChsmfks5q1o_ngaJpZM4KZPLT>.

2016-10-25 18:51 UTC, mfaulkinbury commented
Sounds good to me

Sent from my mobile phone

________________________________
From: Julian Verdurmen <notifications@github.com>
Sent: Wednesday, October 19, 2016 4:47:19 PM
To: NLog/NLog.Etw
Cc: Mike Faulkinbury; Author
Subject: Re: [NLog/NLog.Etw] Support for channels (#15)


Releasing this one ASAP as NLog.ETW 4.1?

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/NLog/NLog.Etw/pull/15#issuecomment-254950665>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AJdhi0qf5LqWWo3Hu6U3HGoiWAMChsmfks5q1o_ngaJpZM4KZPLT>.